/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author diegu
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSenhaCad = new javax.swing.JPasswordField();
        txtNomeCad = new javax.swing.JTextField();
        BtnCadastrar = new javax.swing.JButton();
        txtEmailCad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Cadastro");
        setMinimumSize(new java.awt.Dimension(798, 620));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSenhaCad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtSenhaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 360, 40));

        txtNomeCad.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtNomeCad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtNomeCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 360, 40));

        BtnCadastrar.setBackground(new java.awt.Color(102, 153, 255));
        BtnCadastrar.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        BtnCadastrar.setBorder(null);
        BtnCadastrar.setContentAreaFilled(false);
        BtnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 240, 100));

        txtEmailCad.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtEmailCad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(txtEmailCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 360, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cadastro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        
        JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso");
        this.setVisible(false);
        
    }//GEN-LAST:event_BtnCadastrarActionPerformed

    public boolean checkLogin(String login, String senha){
        return login.equals("funcionario") && senha.equals("123");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmailCad;
    private javax.swing.JTextField txtNomeCad;
    private javax.swing.JPasswordField txtSenhaCad;
    // End of variables declaration//GEN-END:variables
}
