/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;


import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diegu
 */
public class TelaVisualizaçãoDoChamados extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAvaliação1
     */
    public TelaVisualizaçãoDoChamados() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnExcluirVizu = new javax.swing.JButton();
        BtnAbrirChamadoVizu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTChamados = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Chamados");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnExcluirVizu.setBackground(new java.awt.Color(102, 153, 255));
        BtnExcluirVizu.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        BtnExcluirVizu.setForeground(new java.awt.Color(255, 255, 255));
        BtnExcluirVizu.setBorder(null);
        BtnExcluirVizu.setContentAreaFilled(false);
        BtnExcluirVizu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnExcluirVizu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirVizuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExcluirVizu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 120, 40));

        BtnAbrirChamadoVizu.setBackground(new java.awt.Color(102, 153, 255));
        BtnAbrirChamadoVizu.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        BtnAbrirChamadoVizu.setForeground(new java.awt.Color(255, 255, 255));
        BtnAbrirChamadoVizu.setBorder(null);
        BtnAbrirChamadoVizu.setContentAreaFilled(false);
        BtnAbrirChamadoVizu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnAbrirChamadoVizu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbrirChamadoVizuActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAbrirChamadoVizu, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 120, 40));

        JTChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Assunto", "Telefone", "Endereço"
            }
        ));
        JTChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTChamadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTChamados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 220, 550, 360));
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TelaVisualizaçãoDeChamados.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void BtnExcluirVizuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirVizuActionPerformed
        if(JTChamados.getSelectedRow() != -1){
            DefaultTableModel model = (DefaultTableModel) JTChamados.getModel();
            model.removeRow((JTChamados.getSelectedRow()));
            JOptionPane.showMessageDialog(null, "Chamado excluído com sucesso!");
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um chamado!");
        }
    }//GEN-LAST:event_BtnExcluirVizuActionPerformed

    private void BtnAbrirChamadoVizuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbrirChamadoVizuActionPerformed
        
        TelaAberturaDeChamados frameText = new TelaAberturaDeChamados();
        frameText.setVisible(true);
        frameText.pack();
        frameText.setLocationRelativeTo(null);
        frameText.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_BtnAbrirChamadoVizuActionPerformed

    public static void AddLinhaJTable(Object[] dataLinha)
        {   
        DefaultTableModel model = (DefaultTableModel) JTChamados.getModel();
        model.addRow(dataLinha);
    }
    
    private void JTChamadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTChamadosMouseClicked
       
    }//GEN-LAST:event_JTChamadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbrirChamadoVizu;
    private javax.swing.JButton BtnExcluirVizu;
    private static javax.swing.JTable JTChamados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    // End of variables declaration//GEN-END:variables
}
